# Generated by Django 2.2 on 2019-05-11 16:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orderWindows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='books/', verbose_name='菜品图片')),
                ('dish_no', models.CharField(max_length=11, verbose_name='菜品编号')),
                ('name', models.CharField(max_length=200, verbose_name='菜品名称')),
                ('order_num', models.IntegerField(verbose_name='订购数量')),
                ('love_num', models.IntegerField(verbose_name='收藏量')),
                ('desc', models.CharField(max_length=200, verbose_name='菜品描述')),
                ('detail', models.CharField(max_length=1000, verbose_name='菜品详情')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderWindows.WindowInfo', verbose_name='所属窗口')),
            ],
            options={
                'verbose_name': '菜品信息',
                'verbose_name_plural': '菜品信息',
            },
        ),
    ]
