# Generated by Django 2.2 on 2019-05-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishinfo',
            name='price',
            field=models.FloatField(default=1, verbose_name='价格'),
            preserve_default=False,
        ),
    ]
