# Generated by Django 2.2 on 2019-05-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20190511_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.BooleanField(default=1, verbose_name='订购状态'),
            preserve_default=False,
        ),
    ]
