# Generated by Django 2.2 on 2019-05-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='check_status',
            field=models.CharField(choices=[(0, '未审核'), (1, '审核通过'), (2, '审核不通过')], default=0, max_length=10, verbose_name='商家审核状态'),
        ),
    ]
