# Generated by Django 2.2 on 2019-05-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_order_check_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='check_status',
            field=models.CharField(choices=[(0, '未审核'), (1, '已接单'), (2, '交易已完成')], default=0, max_length=10, verbose_name='商家审核状态'),
        ),
    ]
