# Generated by Django 2.2 on 2019-05-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_auto_20190515_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.IntegerField(default=1, verbose_name='订购数量'),
            preserve_default=False,
        ),
    ]
