# Generated by Django 2.2 on 2019-05-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='address',
            field=models.CharField(default=1, max_length=100, verbose_name='地址'),
            preserve_default=False,
        ),
    ]
