# Generated by Django 2.2 on 2019-05-20 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userinfo_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='type',
        ),
    ]
