# Generated by Django 2.2 on 2019-05-22 13:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderWindows', '0003_auto_20190512_2339'),
        ('users', '0003_remove_userinfo_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='快递员姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('manage_window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderWindows.WindowInfo', verbose_name='配送窗口')),
            ],
            options={
                'verbose_name': '快递员信息',
                'verbose_name_plural': '快递员信息',
            },
        ),
    ]
