# Generated by Django 2.2 on 2019-05-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderWindows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowinfo',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='窗口图片'),
            preserve_default=False,
        ),
    ]
