# Generated by Django 2.2 on 2019-05-12 23:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderWindows', '0002_windowinfo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类型名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '窗口类别信息',
                'verbose_name_plural': '窗口类别信息',
            },
        ),
        migrations.AddField(
            model_name='windowinfo',
            name='window_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orderWindows.WindowType', verbose_name='窗口类别'),
            preserve_default=False,
        ),
    ]
